parameter_defaults:
  CinderEnableIscsiBackend: false
  CinderEnableRbdBackend: true
  CinderBackupBackend: ceph
  NovaEnableRbdBackend: true
  GlanceBackend: rbd
  GnocchiBackend: rbd

  CephAnsibleDisksConfig:
    devices:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/sde
      - /dev/sdf
      - /dev/sdg
    osd_scenario: lvm
    osd_objectstore: bluestore
    journal_size: 8192
  CephAnsibleExtraConfig:
    ceph_osd_docker_memory_limit: 3g
    ceph_osd_docker_cpu_limit: 1
    osd_recovery_op_priority: 3
    osd_recovery_max_active: 3
    osd_max_backfills: 1
    osds_per_device: 1

  CephPoolDefaultPgNum: 32
  CephPoolDefaultSize: 3
